# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
